apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: preme-n8n
spec:
  template:
    spec:
      containers:
      - name: n8n
        env:
        - name: N8N_PORT
          value: "5678"
        - name: N8N_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: N8N_WORKER_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: N8N_DIAGNOSTICS_ENABLED
          value: "false"
        - name: N8N_RUNNERS_AUTH_TOKEN
          value: "premeIsMegaCool"
        - name: EXEC_ENV_VARS_ENABLED
          value: "true"
        - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
          value: "false"
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: "puppeteer-extra,puppeteer-extra-plugin-stealth,puppeteer-core"
        envFrom:
        - configMapRef:
            name: n8n-app-config
        - secretRef:
            name: n8n-app-secret
        - secretRef:
            name: scraper-creds
      - name: task-runner
        env:
        - name: EXEC_ENV_VARS_ENABLED
          value: "true"
        - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
          value: "false"
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: "puppeteer-extra,puppeteer-extra-plugin-stealth,puppeteer-core"
        envFrom:
        - secretRef:
            name: scraper-creds
