apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: preme-n8n
spec:
  template:
    spec:
      containers:
      - name: n8n
        env:
        - name: N8N_PORT
          value: "5678"
        - name: N8N_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: N8N_WORKER_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: N8N_DIAGNOSTICS_ENABLED
          value: "false"
        - name: N8N_RUNNERS_AUTH_TOKEN
          value: "premeIsMegaCool"
        - name: EXEC_ENV_VARS_ENABLED
          value: "true"
        - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
          value: "false"
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: "*"
        - name: N8N_RUNNERS_ENABLED
          value: "true"
        - name: N8N_RUNNERS_INSECURE_MODE
          value: "true"
        - name: N8N_RUNNERS_MODE
          value: "external"
        envFrom:
        - configMapRef:
            name: n8n-app-config
        - secretRef:
            name: n8n-app-secret
        - secretRef:
            name: scraper-creds
      - name: task-runner
        image: registry.preme-mgmt.con.idst.ibaintern.de/sep61-aat/preme-n8n-runner:1.0.4
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: EXEC_ENV_VARS_ENABLED
          value: "true"
        - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
          value: "false"
        - name: N8N_RUNNERS_AUTH_TOKEN
          value: "premeIsMegaCool"
        - name: N8N_RUNNERS_N8N_URI
          value: "http://localhost:5678"
        - name: PUPPETEER_EXECUTABLE_PATH
          value: "/usr/bin/chromium-browser"
        - name: NODE_FUNCTION_ALLOW_EXTERNAL
          value: "puppeteer-extra,puppeteer-extra-plugin-stealth,puppeteer-core"
        envFrom:
        - secretRef:
            name: scraper-creds
