apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: preme-n8n
spec:
  template:
    spec:
      containers:
      - name: n8n
        env:
        - name: N8N_PORT
          value: "5678"
        - name: N8N_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: N8N_WORKER_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: N8N_DIAGNOSTICS_ENABLED
          value: "false"
        envFrom:
        - secretRef:
            name: scraper-creds
