apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: smtp-external
  namespace: preme-n8n
spec:
  hosts:
  - smtpex1.baintern.de
  ports:
  - number: 25
    name: smtp
    protocol: TCP
  - number: 587
    name: smtp-submission
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: DNS
  exportTo:
  - "."
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: smtp-external
  namespace: preme-n8n
spec:
  host: smtpex1.baintern.de
  exportTo:
  - "."
  trafficPolicy:
    tls:
      mode: DISABLE
    portLevelSettings:
    - port:
        number: 25
      tls:
        mode: DISABLE
    - port:
        number: 587
      tls:
        mode: DISABLE
